version: v2

managed:
  enabled: true
  override:
    - file_option: go_package
      path: conf/v1
      value: go-wind-admin/api/gen/go/oss_config/v1;ossconfig

plugins:
  - local: protoc-gen-go
    out: gen/go
    opt: paths=source_relative
